sonar.projectKey=IUP_Teacher_Service  # Unga SonarCloud project key
sonar.organization=kojithan-yogarajah # Unga SonarCloud organization key
sonar.host.url=https://sonarcloud.io

# Inga thaan unga code irukku nu sollurom
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/*.test.js

# Encoding
sonar.sourceEncoding=UTF-8